import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "ms";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    const keys = key.split(".");
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  en: {
    nav: {
      home: "Home",
      about: "About Us",
      services: "Services",
      managementSystems: "Management Systems",
      consultants: "Our Consultants",
      courses: "Courses",
      contact: "Contact",
      getQuote: "Get a Quote",
    },
    footer: {
      description: "Leading ISO certification consultancy in Malaysia since 1995. Inspiring excellence through quality and integrity.",
      quickLinks: "Quick Links",
      isoStandards: "ISO Standards",
      contactUs: "Contact Us",
      mofRegistered: "MOF Registered",
      hrdCorp: "HRD Corp",
      allRightsReserved: "All rights reserved",
    },
    home: {
      heroTitle: "QAI",
      heroSubtitle: "Inspiring Excellence Through Quality & Integrity Since 1995",
      heroDescription: "Leading ISO certification consultancy serving Malaysia, Indonesia, and Singapore",
      getFreeQuote: "Get a Free Quote",
      learnMore: "Learn More",
      yearsOfExcellence: "Years of Excellence",
      satisfiedClients: "Satisfied Clients",
      countriesServed: "Countries Served",
      certificationsCompleted: "Certifications Completed",
      isoManagementSystems: "ISO Management Systems",
      isoManagementSystemsDesc: "Comprehensive certification, training, and consulting services for international quality standards",
      iso9001Desc: "Quality Management System for operational excellence and customer satisfaction",
      iso14001Desc: "Environmental Management System for sustainable business practices",
      iso45001Desc: "Occupational Health & Safety Management for workplace protection",
      iso27001Desc: "Information Security Management for data protection and cybersecurity",
      iso37001Desc: "Anti-Bribery Management System for corruption prevention",
      iso21001Desc: "Educational Organisations Management for quality in learning",
      ourServices: "Our Services",
      ourServicesDesc: "End-to-end solutions for ISO certification and quality management",
      trainingServices: "Training Services",
      trainingServicesDesc: "Public courses, in-house training, and customized programs. HRD Corp claimable courses available.",
      consultingServices: "Consulting Services",
      consultingServicesDesc: "ISO implementation, gap analysis, documentation development, and system maintenance support.",
      auditingServices: "Auditing Services",
      auditingServicesDesc: "Internal audits, surveillance audits, pre-certification, and second-party auditing.",
      readyToCertify: "Ready to Get Certified?",
      readyToCertifyDesc: "Connect with our expert consultants and start your ISO certification journey today",
      scheduleConsultation: "Schedule Consultation",
      meetOurTeam: "Meet Our Team",
    },
    about: {
      title: "About QAI",
      subtitle: "Three decades of excellence in ISO certification, training, and consulting services",
      whoWeAre: "Who We Are",
      para1: "QAI Sdn Bhd (Quality Assurance International) was incorporated in August 1995 with a clear vision — to inspire and empower organizations to achieve excellence through quality, integrity, and continuous improvement.",
      para2: "Beginning with a focus on ISO 9001 (Quality Management System), QAI has progressively expanded its expertise to include ISO 14001 (Environmental Management System), ISO 27001 (Information Security Management System), ISO 45001 (Occupational Health and Safety Management System), and ISO 37001 (Anti-Bribery Management System), along with Kaizen and Lean Management practices.",
      para3: "For nearly three decades, QAI has been a trusted partner in providing training, consulting, and auditing services across Malaysia and ASEAN countries, including Indonesia and Singapore.",
      para4: "Through unwavering commitment, professionalism, and adaptability, QAI has successfully sustained its growth and reputation amidst the changing business and economic landscapes — continuing to uphold its mission of enhancing organizational performance and promoting a culture of excellence.",
      ourVision: "Our Vision",
      visionText: "To assist clients to operate cost effective competitive businesses using the ISO Quality Management System Standards as the basis for continual improvement. QAI achieves this by facilitating clients to proactively look at areas of potential and achievable improvements and adopt innovative, practical and realistic targets over a set timeframe.",
      ourMission: "Our Mission",
      missionText: "Committed in providing excellent training and consultancy services to all clients by:",
      mission1: "Ensuring innovative and effective knowledge transfer",
      mission2: "Facilitating and enhancing management competency",
      mission3: "Delivering effective solutions across the clients' organization",
      qualityPolicy: "Quality Policy",
      qualityPolicyText: "Committed in providing value and excellent training and consulting services that comply with clients' requirements through continual improvement and effective quality management system.",
      ourJourney: "Our Journey",
      timeline: {
        1995: "QAI established, beginning our journey in quality management consulting",
        2000: "Expanded services to include ISO 14001 environmental management",
        2005: "Reached milestone of 500+ successful certifications",
        2010: "Extended operations to Indonesia and Singapore",
        2015: "Celebrated 20 years of excellence with 2000+ clients served",
        2020: "Launched comprehensive online training programs",
        2025: "30 years of inspiring excellence in quality management",
      },
      certificationsRegistrations: "Certifications & Registrations",
      registrationNumber: "Registration Number",
      mofCertificateNo: "MOF Certificate No",
      mofRegRefNo: "MOF Reg. Ref. No",
      mofValidationPeriod: "MOF Validation Period",
      bumiputeraCertificateNo: "Bumiputera Certificate No",
      hrdCorpProvider: "HRD CORP Registered Training Provider",
      ourGeographicReach: "Our Geographic Reach",
      malaysiaDesc: "Headquarters in Puchong with nationwide coverage",
      indonesiaDesc: "Serving major business centers across the archipelago",
      singaporeDesc: "Supporting enterprises in the financial hub of Southeast Asia",
    },
    iso: {
      qualityManagement: "Quality Management",
      environmentalManagement: "Environmental Management",
      occupationalHealthSafety: "Occupational Health & Safety Management",
      informationSecurity: "Information Security Management System",
      antiBribery: "Anti-Bribery Management System",
    },
  },
  ms: {
    nav: {
      home: "Laman Utama",
      about: "Tentang Kami",
      services: "Perkhidmatan",
      managementSystems: "Sistem Pengurusan",
      consultants: "Perunding Kami",
      courses: "Kursus",
      contact: "Hubungi",
      getQuote: "Dapatkan Sebut Harga",
    },
    footer: {
      description: "Perunding pensijilan ISO terkemuka di Malaysia sejak 1995. Memberi inspirasi kecemerlangan melalui kualiti dan integriti.",
      quickLinks: "Pautan Pantas",
      isoStandards: "Piawaian ISO",
      contactUs: "Hubungi Kami",
      mofRegistered: "Berdaftar MOF",
      hrdCorp: "HRD Corp",
      allRightsReserved: "Hak cipta terpelihara",
    },
    home: {
      heroTitle: "QAI",
      heroSubtitle: "Memberi Inspirasi Kecemerlangan Melalui Kualiti & Integriti Sejak 1995",
      heroDescription: "Perunding pensijilan ISO terkemuka yang melayani Malaysia, Indonesia, dan Singapura",
      getFreeQuote: "Dapatkan Sebut Harga Percuma",
      learnMore: "Ketahui Lebih Lanjut",
      yearsOfExcellence: "Tahun Kecemerlangan",
      satisfiedClients: "Pelanggan Berpuas Hati",
      countriesServed: "Negara Dilayani",
      certificationsCompleted: "Pensijilan Selesai",
      isoManagementSystems: "Sistem Pengurusan ISO",
      isoManagementSystemsDesc: "Pensijilan, latihan, dan perkhidmatan perundingan yang komprehensif untuk piawaian kualiti antarabangsa",
      iso9001Desc: "Sistem Pengurusan Kualiti untuk kecemerlangan operasi dan kepuasan pelanggan",
      iso14001Desc: "Sistem Pengurusan Alam Sekitar untuk amalan perniagaan yang mampan",
      iso45001Desc: "Pengurusan Kesihatan & Keselamatan Pekerjaan untuk perlindungan tempat kerja",
      iso27001Desc: "Pengurusan Keselamatan Maklumat untuk perlindungan data dan keselamatan siber",
      iso37001Desc: "Sistem Pengurusan Anti-Rasuah untuk pencegahan rasuah",
      iso21001Desc: "Pengurusan Organisasi Pendidikan untuk kualiti dalam pembelajaran",
      ourServices: "Perkhidmatan Kami",
      ourServicesDesc: "Penyelesaian menyeluruh untuk pensijilan ISO dan pengurusan kualiti",
      trainingServices: "Perkhidmatan Latihan",
      trainingServicesDesc: "Kursus awam, latihan dalaman, dan program tersuai. Kursus boleh dituntut HRD Corp tersedia.",
      consultingServices: "Perkhidmatan Perundingan",
      consultingServicesDesc: "Pelaksanaan ISO, analisis jurang, pembangunan dokumentasi, dan sokongan penyelenggaraan sistem.",
      auditingServices: "Perkhidmatan Audit",
      auditingServicesDesc: "Audit dalaman, audit pengawasan, pra-pensijilan, dan audit pihak kedua.",
      readyToCertify: "Bersedia untuk Disijilkan?",
      readyToCertifyDesc: "Hubungi perunding pakar kami dan mulakan perjalanan pensijilan ISO anda hari ini",
      scheduleConsultation: "Jadualkan Perundingan",
      meetOurTeam: "Temui Pasukan Kami",
    },
    about: {
      title: "Tentang QAI",
      subtitle: "Tiga dekad kecemerlangan dalam pensijilan ISO, latihan, dan perkhidmatan perundingan",
      whoWeAre: "Siapa Kami",
      para1: "QAI Sdn Bhd (Quality Assurance International) telah diperbadankan pada Ogos 1995 dengan visi yang jelas — untuk memberi inspirasi dan memperkasakan organisasi untuk mencapai kecemerlangan melalui kualiti, integriti, dan penambahbaikan berterusan.",
      para2: "Bermula dengan fokus kepada ISO 9001 (Sistem Pengurusan Kualiti), QAI telah mengembangkan kepakarannya secara progresif untuk merangkumi ISO 14001 (Sistem Pengurusan Alam Sekitar), ISO 27001 (Sistem Pengurusan Keselamatan Maklumat), ISO 45001 (Sistem Pengurusan Kesihatan dan Keselamatan Pekerjaan), dan ISO 37001 (Sistem Pengurusan Anti-Rasuah), bersama-sama dengan amalan Kaizen dan Lean Management.",
      para3: "Selama hampir tiga dekad, QAI telah menjadi rakan kongsi yang dipercayai dalam menyediakan perkhidmatan latihan, perundingan, dan audit di seluruh Malaysia dan negara-negara ASEAN, termasuk Indonesia dan Singapura.",
      para4: "Melalui komitmen yang tidak berbelah bahagi, profesionalisme, dan kebolehsuaian, QAI telah berjaya mengekalkan pertumbuhan dan reputasinya di tengah-tengah perubahan landskap perniagaan dan ekonomi — terus menegakkan misinya untuk meningkatkan prestasi organisasi dan mempromosikan budaya kecemerlangan.",
      ourVision: "Visi Kami",
      visionText: "Untuk membantu pelanggan mengendalikan perniagaan yang kompetitif dengan kos efektif menggunakan Piawaian Sistem Pengurusan Kualiti ISO sebagai asas untuk penambahbaikan berterusan. QAI mencapai ini dengan memudahkan pelanggan untuk secara proaktif melihat bidang penambahbaikan yang berpotensi dan boleh dicapai serta menggunakan sasaran yang inovatif, praktikal dan realistik dalam jangka masa yang ditetapkan.",
      ourMission: "Misi Kami",
      missionText: "Komited dalam menyediakan perkhidmatan latihan dan perundingan yang cemerlang kepada semua pelanggan dengan:",
      mission1: "Memastikan pemindahan pengetahuan yang inovatif dan berkesan",
      mission2: "Memudahkan dan meningkatkan kecekapan pengurusan",
      mission3: "Menyampaikan penyelesaian yang berkesan di seluruh organisasi pelanggan",
      qualityPolicy: "Dasar Kualiti",
      qualityPolicyText: "Komited dalam menyediakan nilai dan perkhidmatan latihan serta perundingan yang cemerlang yang mematuhi keperluan pelanggan melalui penambahbaikan berterusan dan sistem pengurusan kualiti yang berkesan.",
      ourJourney: "Perjalanan Kami",
      timeline: {
        1995: "QAI ditubuhkan, memulakan perjalanan kami dalam perundingan pengurusan kualiti",
        2000: "Perkhidmatan dikembangkan untuk merangkumi pengurusan alam sekitar ISO 14001",
        2005: "Mencapai pencapaian 500+ pensijilan yang berjaya",
        2010: "Memperluaskan operasi ke Indonesia dan Singapura",
        2015: "Meraikan 20 tahun kecemerlangan dengan 2000+ pelanggan yang dilayani",
        2020: "Melancarkan program latihan dalam talian yang komprehensif",
        2025: "30 tahun memberi inspirasi kecemerlangan dalam pengurusan kualiti",
      },
      certificationsRegistrations: "Pensijilan & Pendaftaran",
      registrationNumber: "Nombor Pendaftaran",
      mofCertificateNo: "No. Sijil MOF",
      mofRegRefNo: "No. Rujukan Pendaftaran MOF",
      mofValidationPeriod: "Tempoh Pengesahan MOF",
      bumiputeraCertificateNo: "No. Sijil Bumiputera",
      hrdCorpProvider: "Penyedia Latihan Berdaftar HRD CORP",
      ourGeographicReach: "Jangkauan Geografi Kami",
      malaysiaDesc: "Ibu pejabat di Puchong dengan liputan di seluruh negara",
      indonesiaDesc: "Melayani pusat perniagaan utama di seluruh nusantara",
      singaporeDesc: "Menyokong perusahaan di pusat kewangan Asia Tenggara",
    },
    iso: {
      qualityManagement: "Pengurusan Kualiti",
      environmentalManagement: "Pengurusan Alam Sekitar",
      occupationalHealthSafety: "Pengurusan Kesihatan & Keselamatan Pekerjaan",
      informationSecurity: "Sistem Pengurusan Keselamatan Maklumat",
      antiBribery: "Sistem Pengurusan Anti-Rasuah",
    },
    services: {
      title: "Perkhidmatan Kami",
      subtitle: "Penyelesaian pensijilan ISO yang komprehensif disesuaikan dengan keperluan organisasi anda",
      training: "Perkhidmatan Latihan",
      trainingDesc: "Perkasakan pasukan anda dengan program latihan ISO yang dikendalikan pakar yang direka untuk membina kecekapan dan memastikan pelaksanaan yang berjaya.",
      publicCourses: "Kursus Latihan Awam",
      publicCoursesDesc: "Kursus berjadual terbuka untuk semua peserta dengan pilihan boleh tuntut HRD Corp tersedia.",
      inHouse: "Latihan Dalaman",
      inHouseDesc: "Program tersuai disampaikan di lokasi anda, disesuaikan dengan keperluan khusus anda.",
      online: "Latihan Dalam Talian/Maya",
      onlineDesc: "Penyelesaian e-pembelajaran yang fleksibel dengan sesi secara langsung yang dikendalikan oleh pengajar dan bahan interaktif.",
      awareness: "Kursus Kesedaran",
      awarenessDesc: "Pengenalan kepada piawaian ISO dan asas sistem pengurusan",
      implementer: "Kursus Pelaksana",
      implementerDesc: "Kemahiran praktikal untuk melaksanakan sistem pengurusan ISO",
      internalAuditor: "Juruaudit Dalaman",
      internalAuditorDesc: "Latihan komprehensif untuk menjalankan audit dalaman yang berkesan",
      leadAuditor: "Juruaudit Utama",
      leadAuditorDesc: "Pensijilan lanjutan untuk kelayakan juruaudit utama ISO",
      consulting: "Perkhidmatan Perundingan",
      consultingDesc: "Bimbingan pakar dari analisis jurang awal melalui pensijilan yang berjaya dan seterusnya",
      gapAnalysis: "Analisis Jurang",
      gapAnalysisDesc: "Menilai amalan semasa berbanding keperluan ISO",
      systemDesign: "Reka Bentuk Sistem",
      systemDesignDesc: "Membangunkan rangka kerja sistem pengurusan yang disesuaikan",
      implementation: "Pelaksanaan",
      implementationDesc: "Membimbing pasukan anda melalui penggunaan sistem",
      certSupport: "Sokongan Pensijilan",
      certSupportDesc: "Persediaan pra-audit dan bantuan pensijilan",
      docDev: "Pembangunan Dokumentasi",
      docDevDesc: "Penciptaan manual kualiti, prosedur, arahan kerja, dan dokumentasi yang diperlukan",
      systemMaint: "Penyelenggaraan Sistem",
      systemMaintDesc: "Sokongan berterusan untuk mengekalkan dan meningkatkan prestasi sistem pengurusan anda",
      auditing: "Perkhidmatan Audit",
      auditingDesc: "Perkhidmatan audit profesional untuk mengesahkan pematuhan dan memacu penambahbaikan berterusan",
      internalAudits: "Audit Dalaman",
      internalAuditsDesc: "Audit sistem berkala untuk mengesahkan pematuhan dan mengenal pasti peluang penambahbaikan",
      surveillance: "Audit Pengawasan",
      surveillanceDesc: "Pemantauan berterusan untuk mengekalkan status pensijilan dan keberkesanan sistem",
      preCert: "Audit Pra-Pensijilan",
      preCertDesc: "Audit percubaan untuk memastikan kesediaan untuk penilaian pensijilan rasmi",
      secondParty: "Audit Pihak Kedua",
      secondPartyDesc: "Audit pembekal dan vendor untuk memastikan piawaian kualiti rantaian bekalan",
      industries: "Industri Yang Kami Layani",
      manufacturing: "Pembuatan",
      oilGas: "Minyak & Gas",
      healthcare: "Penjagaan Kesihatan",
      education: "Pendidikan",
      construction: "Pembinaan",
      it: "Teknologi Maklumat",
      government: "Agensi Kerajaan",
      financial: "Perkhidmatan Kewangan",
      hospitality: "Hospitaliti",
      logistics: "Logistik & Pengangkutan",
      foodBev: "Makanan & Minuman",
      professional: "Perkhidmatan Profesional",
    },
    consultants: {
      title: "Perunding Pakar Kami",
      subtitle: "Temui pasukan pakar pensijilan ISO yang berkelayakan tinggi kami dengan pengalaman gabungan berdekad-dekad",
      expertise: "Kepakaran Terkemuka Industri",
      expertiseDesc: "Perunding kami membawa kekayaan pengetahuan dari pelbagai industri dan pasaran antarabangsa. Dengan kelayakan lanjutan, pensijilan profesional, dan pengalaman praktikal yang luas, mereka menyediakan panduan strategik yang menghasilkan hasil sebenar untuk organisasi anda.",
      yearsExp: "Tahun Pengalaman Gabungan",
      certifications: "Pensijilan Profesional",
      countriesServed: "Negara Dilayani",
      trustedBy: "Dipercayai oleh Organisasi Terkemuka",
      meetTeam: "Temui Pasukan Kami",
      workWithExperts: "Bekerja Dengan Pakar Kami",
      workWithExpertsDesc: "Hubungi perunding kami untuk membincangkan keperluan pensijilan ISO anda dan cari penyelesaian yang sesuai untuk organisasi anda",
      requestConsultant: "Minta Perunding",
      viewTraining: "Lihat Program Latihan",
    },
    courses: {
      title: "Kursus Latihan",
      subtitle: "Program latihan pensijilan ISO profesional yang direka untuk membina kecekapan dan memastikan kejayaan",
      publicCourses: "Kursus Awam",
      publicCoursesDesc: "Sertai sesi latihan berjadual kami dengan peserta dari pelbagai organisasi. Sesuai untuk individu atau pasukan kecil.",
      hrdClaimable: "Kursus boleh tuntut HRD Corp tersedia",
      networking: "Rangkaian dengan profesional industri",
      earlyBird: "Harga awal tersedia",
      inHouse: "Latihan Dalaman",
      inHouseDesc: "Latihan tersuai disampaikan di lokasi anda, disesuaikan dengan keperluan khusus organisasi anda dan konteks industri.",
      flexible: "Penjadualan fleksibel mengikut kemudahan anda",
      customized: "Kandungan disesuaikan dengan proses anda",
      costEffective: "Kos efektif untuk pasukan yang lebih besar",
      catalog: "Katalog Kursus Awam",
      catalogDesc: "Layari program latihan kami yang akan datang dan daftar dalam talian",
      duration: "Tempoh",
      awareness: "Kesedaran",
      implementer: "Pelaksana",
      internalAuditor: "Juruaudit Dalaman",
      leadAuditor: "Juruaudit Utama",
      advanced: "Lanjutan",
      hrdCorp: "HRD Corp",
      viewDetails: "Lihat Butiran",
      levels: "Tahap Kursus",
      awarenessDesc: "Pengenalan kepada piawaian ISO dan konsep asas",
      implementerDesc: "Kemahiran praktikal untuk pelaksanaan dan penyelenggaraan sistem",
      auditorDesc: "Latihan komprehensif untuk menjalankan audit dalaman",
      leadAuditorDesc: "Pensijilan lanjutan untuk kelayakan juruaudit utama",
      benefits: "Faedah Latihan",
      benefit1: "Pengajar pakar dengan pengalaman dunia sebenar",
      benefit2: "Bahan kursus dan sumber yang komprehensif",
      benefit3: "Latihan praktikal dan kajian kes",
      benefit4: "Pensijilan antarabangsa selepas selesai",
      benefit5: "Kursus boleh tuntut HRD Corp untuk peserta yang layak",
      benefit6: "Sokongan dan perundingan selepas latihan",
      readyToCertify: "Bersedia untuk Disijilkan?",
      readyToCertifyDesc: "Daftar dalam program latihan kami atau minta penyelesaian latihan dalaman yang disesuaikan",
      registerNow: "Daftar Sekarang",
      requestInHouse: "Minta Latihan Dalaman",
    },
    contact: {
      title: "Hubungi Kami",
      subtitle: "Hubungi pasukan kami untuk membincangkan keperluan pensijilan ISO anda",
      location: "Lokasi Pejabat",
      phone: "Telefon",
      email: "E-mel",
      hours: "Waktu Perniagaan",
      monFri: "Isnin - Jumaat: 9:00 PG - 6:00 PTG",
      sat: "Sabtu: 9:00 PG - 1:00 PTG",
      sendMessage: "Hantar Kami Mesej",
      formDesc: "Isi borang di bawah dan pasukan kami akan menghubungi anda dalam masa 24 jam",
      fullName: "Nama Penuh *",
      emailAddress: "Alamat E-mel *",
      phoneNumber: "Nombor Telefon",
      companyName: "Nama Syarikat",
      serviceInterest: "Minat Perkhidmatan",
      selectService: "Pilih perkhidmatan",
      message: "Mesej *",
      messagePlaceholder: "Beritahu kami tentang keperluan anda...",
      send: "Hantar Mesej",
      visitOffice: "Lawati Pejabat Kami",
      openGoogleMaps: "Buka di Google Maps",
      openAppleMaps: "Buka di Apple Maps",
      messageSent: "Mesej Dihantar!",
      messageSentDesc: "Terima kasih kerana menghubungi kami. Kami akan menghubungi anda dalam masa 24 jam.",
      training: "Perkhidmatan Latihan",
      consulting: "Perkhidmatan Perundingan",
      auditing: "Perkhidmatan Audit",
      iso9001: "Pensijilan ISO 9001",
      iso14001: "Pensijilan ISO 14001",
      iso45001: "Pensijilan ISO 45001",
      iso27001: "Pensijilan ISO 27001",
      iso37001: "Pensijilan ISO 37001",
      other: "Lain-lain",
    },
    iso9001: {
      title: "ISO 9001:2015",
      subtitle: "Sistem Pengurusan Kualiti",
      tagline: "Piawaian pengurusan kualiti yang paling diiktiraf di dunia untuk kecemerlangan operasi",
      whatIs: "Apakah ISO 9001:2015?",
      description1: "ISO 9001:2015 adalah piawaian antarabangsa yang menyatakan keperluan untuk sistem pengurusan kualiti (QMS). Organisasi menggunakan piawaian ini untuk menunjukkan keupayaan mereka untuk secara konsisten menyediakan produk dan perkhidmatan yang memenuhi keperluan pelanggan dan peraturan.",
      description2: "Ia adalah piawaian pengurusan kualiti yang paling banyak digunakan di dunia, membantu organisasi dari semua saiz dan sektor meningkatkan prestasi mereka, memenuhi jangkaan pelanggan, dan menunjukkan komitmen mereka terhadap kualiti.",
      benefits: "Faedah Utama",
      benefit1Title: "Kepuasan Pelanggan yang Dipertingkatkan",
      benefit1Desc: "Memenuhi keperluan pelanggan secara konsisten dan meningkatkan kepuasan melalui aplikasi sistem yang berkesan dan penambahbaikan berterusan.",
      benefit2Title: "Kecekapan Operasi yang Lebih Baik",
      benefit2Desc: "Memperkemas proses, mengurangkan pembaziran, dan meningkatkan produktiviti melalui pendekatan sistematik kepada pengurusan kualiti.",
      benefit3Title: "Penglibatan Pekerja",
      benefit3Desc: "Mewujudkan budaya kesedaran kualiti dan penambahbaikan berterusan, meningkatkan penglibatan dan kecekapan pekerja.",
      benefit4Title: "Kelebihan Daya Saing",
      benefit4Desc: "Menunjukkan komitmen terhadap kualiti, memenangi lebih banyak tender, dan mendapat kelebihan daya saing di pasaran.",
      whoNeeds: "Siapa Yang Memerlukan ISO 9001?",
      manufacturing: "Pembuatan",
      services: "Perkhidmatan",
      healthcare: "Penjagaan Kesihatan",
      education: "Pendidikan",
      construction: "Pembinaan",
      it: "IT & Perisian",
      government: "Kerajaan",
      hospitality: "Hospitaliti",
      logistics: "Logistik",
      financial: "Perkhidmatan Kewangan",
      retail: "Runcit",
      professional: "Perkhidmatan Profesional",
      process: "Proses Pelaksanaan",
      step1: "Analisis Jurang",
      step1Desc: "Menilai amalan semasa berbanding keperluan ISO 9001",
      step2: "Perancangan & Reka Bentuk",
      step2Desc: "Membangunkan rangka kerja QMS dan struktur dokumentasi",
      step3: "Pelaksanaan",
      step3Desc: "Menggunakan sistem, melatih kakitangan, dan mewujudkan proses",
      step4: "Pensijilan",
      step4Desc: "Audit dalaman, semakan pengurusan, dan audit pensijilan",
      cta: "Bersedia untuk Disijilkan ISO 9001?",
      ctaDesc: "Hubungi perunding pakar kami dan mulakan perjalanan pengurusan kualiti anda",
      requestConsultation: "Minta Perundingan",
      viewCourses: "Lihat Kursus Latihan",
    },
    iso14001: {
      title: "ISO 14001:2015",
      subtitle: "Sistem Pengurusan Alam Sekitar",
      tagline: "Tunjukkan komitmen anda terhadap kemampanan alam sekitar dan pematuhan peraturan",
      whatIs: "Apakah ISO 14001:2015?",
      description1: "ISO 14001:2015 menetapkan kriteria untuk sistem pengurusan alam sekitar (EMS). Ia memetakan rangka kerja yang boleh diikuti oleh organisasi untuk menyediakan sistem pengurusan alam sekitar yang berkesan, membantu mereka meningkatkan prestasi alam sekitar melalui penggunaan sumber yang lebih cekap dan pengurangan pembaziran.",
      description2: "Piawaian ini boleh digunakan untuk mana-mana organisasi, tanpa mengira saiz, jenis, atau sifat, dan boleh disepadukan dengan keperluan sistem pengurusan lain untuk membantu organisasi mencapai matlamat alam sekitar dan ekonomi.",
      benefits: "Faedah Alam Sekitar",
      benefit1Title: "Kecekapan Sumber",
      benefit1Desc: "Mengurangkan pembaziran, mengoptimumkan penggunaan sumber, dan meminimumkan jejak alam sekitar melalui pengurusan alam sekitar yang sistematik.",
      benefit2Title: "Pematuhan Peraturan",
      benefit2Desc: "Memastikan pematuhan dengan peraturan alam sekitar dan menunjukkan ketekunan wajar dalam perlindungan alam sekitar.",
      benefit3Title: "Penjimatan Kos",
      benefit3Desc: "Mengurangkan penggunaan tenaga, kos pelupusan sisa, dan liabiliti alam sekitar sambil meningkatkan keuntungan.",
      benefit4Title: "Reputasi Jenama",
      benefit4Desc: "Meningkatkan imej korporat dan keyakinan pihak berkepentingan melalui tanggungjawab alam sekitar yang ditunjukkan.",
      cta: "Mulakan Perjalanan Alam Sekitar Anda",
      ctaDesc: "Laksanakan ISO 14001 dan tunjukkan komitmen anda terhadap kemampanan alam sekitar",
      getStarted: "Mulakan",
      trainingPrograms: "Program Latihan",
    },
    iso27001: {
      title: "ISO 27001:2022",
      subtitle: "Sistem Pengurusan Keselamatan Maklumat",
      tagline: "Lindungi data anda dan tunjukkan amalan keselamatan maklumat bertaraf dunia",
      whatIs: "Apakah ISO 27001:2022?",
      description1: "ISO 27001:2022 adalah piawaian antarabangsa untuk sistem pengurusan keselamatan maklumat (ISMS). Ia menyediakan pendekatan sistematik untuk mengurus maklumat syarikat yang sensitif, memastikan ia kekal selamat melalui kawalan orang, proses, dan teknologi.",
      description2: "Pada era digital hari ini, melindungi aset maklumat adalah kritikal. ISO 27001 membantu organisasi mengurus keselamatan aset seperti maklumat kewangan, harta intelek, butiran pekerja, dan maklumat yang diamanahkan oleh pihak ketiga.",
      benefits: "Faedah Keselamatan",
      benefit1Title: "Perlindungan Data",
      benefit1Desc: "Melindungi maklumat sulit dan memastikan kerahsiaan, integriti, dan ketersediaan aset data kritikal.",
      benefit2Title: "Pengurusan Ancaman Siber",
      benefit2Desc: "Mengenal pasti, menilai, dan mengurangkan risiko keselamatan siber melalui pendekatan pengurusan risiko yang sistematik.",
      benefit3Title: "Pematuhan Peraturan",
      benefit3Desc: "Memenuhi peraturan perlindungan data termasuk GDPR, PDPA, dan keperluan privasi lain.",
      benefit4Title: "Kepercayaan Pelanggan",
      benefit4Desc: "Membina keyakinan pihak berkepentingan dan kelebihan daya saing melalui komitmen keselamatan yang ditunjukkan.",
      cta: "Amankan Aset Maklumat Anda",
      ctaDesc: "Laksanakan ISO 27001 dan lindungi organisasi anda dari ancaman keselamatan maklumat",
      getProtected: "Dapatkan Perlindungan",
      securityTraining: "Latihan Keselamatan",
    },
    iso37001: {
      title: "ISO 37001:2018",
      subtitle: "Sistem Pengurusan Anti-Rasuah",
      tagline: "Perangi rasuah dan tunjukkan komitmen anda terhadap amalan perniagaan yang beretika",
      whatIs: "Apakah ISO 37001:2018?",
      description1: "ISO 37001:2018 menyatakan keperluan dan menyediakan panduan untuk mewujudkan, melaksanakan, mengekalkan, mengkaji, dan meningkatkan sistem pengurusan anti-rasuah (ABMS). Sistem ini boleh berdiri sendiri atau disepadukan ke dalam sistem pengurusan keseluruhan.",
      description2: "Ia menangani rasuah dalam sektor awam, swasta, dan bukan keuntungan, membantu organisasi melaksanakan atau meningkatkan kawalan untuk membantu mencegah, mengesan, dan bertindak balas terhadap rasuah dan mematuhi undang-undang anti-rasuah dan komitmen sukarela.",
      benefits: "Faedah Tadbir Urus",
      benefit1Title: "Pematuhan Undang-undang",
      benefit1Desc: "Menunjukkan pematuhan dengan undang-undang anti-rasuah dan anti-rasuah termasuk Akta SPRM dan perundangan antarabangsa.",
      benefit2Title: "Tadbir Urus Korporat",
      benefit2Desc: "Mengukuhkan rangka kerja tadbir urus dan menunjukkan komitmen terhadap tingkah laku perniagaan yang beretika di semua peringkat.",
      benefit3Title: "Keyakinan Pihak Berkepentingan",
      benefit3Desc: "Membina kepercayaan dengan pelabur, rakan kongsi, dan pelanggan melalui dasar dan kawalan anti-rasuah yang telus.",
      benefit4Title: "Peluang Perniagaan",
      benefit4Desc: "Mengakses kontrak kerajaan dan pasaran antarabangsa yang memerlukan pensijilan anti-rasuah.",
      cta: "Kukuhkan Integriti Anda",
      ctaDesc: "Laksanakan ISO 37001 dan bina budaya pematuhan dan tingkah laku beretika",
      startJourney: "Mulakan Perjalanan Anda",
      abmsTraining: "Latihan ABMS",
    },
    iso45001: {
      title: "ISO 45001:2018",
      subtitle: "Pengurusan Kesihatan & Keselamatan Pekerjaan",
      tagline: "Lindungi tenaga kerja anda dan cipta persekitaran kerja yang lebih selamat dan sihat",
      whatIs: "Apakah ISO 45001:2018?",
      description1: "ISO 45001:2018 adalah piawaian antarabangsa dunia untuk kesihatan dan keselamatan pekerjaan (OH&S). Ia menyediakan rangka kerja untuk meningkatkan keselamatan, mengurangkan risiko tempat kerja, dan meningkatkan kesihatan dan kesejahteraan di tempat kerja, membolehkan organisasi meningkatkan prestasi OH&S mereka secara proaktif.",
      description2: "Piawaian ini membantu organisasi menyediakan tempat kerja yang selamat dan sihat dengan mencegah kecederaan dan penyakit berkaitan kerja, serta dengan meningkatkan prestasi OH&S secara proaktif.",
      benefits: "Faedah Keselamatan",
      benefit1Title: "Keselamatan Pekerja",
      benefit1Desc: "Mengurangkan kemalangan tempat kerja, kecederaan, dan penyakit pekerjaan melalui pengurusan risiko dan pencegahan yang sistematik.",
      benefit2Title: "Pengurangan Risiko",
      benefit2Desc: "Mengenal pasti, menilai, dan mengawal risiko kesihatan dan keselamatan secara proaktif untuk mencegah insiden sebelum ia berlaku.",
      benefit3Title: "Semangat Pekerja",
      benefit3Desc: "Meningkatkan penglibatan dan semangat pekerja dengan menunjukkan komitmen terhadap kesihatan, keselamatan, dan kesejahteraan mereka.",
      benefit4Title: "Pematuhan Undang-undang",
      benefit4Desc: "Memastikan pematuhan dengan perundangan kesihatan dan keselamatan pekerjaan dan mengurangkan liabiliti undang-undang.",
      cta: "Utamakan Keselamatan Tempat Kerja",
      ctaDesc: "Laksanakan ISO 45001 dan cipta persekitaran kerja yang lebih selamat dan sihat",
      scheduleConsultation: "Jadualkan Perundingan",
      ohsTraining: "Latihan OH&S",
    },
  },
};
